--- 
- 
  connection: local
  gather_facts: false
  hosts: localhost
  tasks: 
    - 
      containers: 
        - 
          cpu: 1
          essential: true
          family: test-cluster-taskdef
          image: 012680547479.dkr.ecr.us-east-1.amazonaws.com/testrepo
          memory: 300
          name: simple-app
          portMappings: 
            - 
              containerPort: 80
              hostPort: 9001
          revision: 10
          state: present
      ecs_taskdefinition: ~
      name: "Create task definition"
    - 
      cluster: mycluster
      deployment_configuration: 
        maximum_percent: 150
        minimum_healthy_percent: 75
      desired_count: 3
      ecs_service: ~
      name: console-test-service
      state: present
      task_definition: "simple-app:10"

