- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create task definition
      ecs_taskdefinition:
      containers:
      - name: simple-app
        cpu: 1
        essential: true
        image: 012680547479.dkr.ecr.us-east-1.amazonaws.com/testrepo
        memory: 300
        portMappings:
        - containerPort: 80
          hostPort: 9001
        family: test-cluster-taskdef
        state: present
        revision: 10
  register: task_output
    - name: Create Service 
      ecs_service:
      state: present
      name: console-test-service
      cluster: mycluster
      task_definition: simple-app:10
      desired_count: 3
      deployment_configuration:
        minimum_healthy_percent: 75
        maximum_percent: 150
